version: '3.4'

services:
  bluraycollectionapi:
    image: ${DOCKER_REGISTRY-}bluraycollectionapi
    ports:
      - "55343:8080"
      - "55344:8081"
    build:
      context: .
      dockerfile: BluRayCollectionAPI/Dockerfile
  mongo:
     image: mongo
     restart: always
     ports:
       - "27017:27017"
     volumes:
          - ./data:/data/db
     environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 32799:8082
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password